set_property SRC_FILE_INFO {cfile:C:/Users/corey/repos/vivado/BlinkingLED/BlinkingLED.srcs/constrs_1/imports/vivado/Arty-S7-50-Master.xdc rfile:../../../BlinkingLED.srcs/constrs_1/imports/vivado/Arty-S7-50-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R2    IOSTANDARD SSTL135 } [get_ports clk]; #IO_L12P_T1_MRCC_34 Sch=ddr3_clk[200]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports led]; #IO_L16N_T2_A27_15 Sch=led[2]
